config/routes.rb
Rails.application.routes.draw do
  root to: 'expenses#index'

  get    '/signin'  => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  match  '/auth/:provider/callback' => 'sessions#create',  via: [:get, :post]
  get    '/auth/failure'            => 'sessions#failure'

  resources :users, except: [:new, :edit, :destroy]
  get '/signup'  => 'users#new'
  get '/profile' => 'users#edit'

  resources :expenses, except: [:new, :edit]
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user

  validates :amount, presence: true

  before_validation :set_defaults

  private

  def set_defaults
    self.accrued_on ||= Time.zone.today
  end
end

app/models/user.rb
class User < OmniAuth::Identity::Models::ActiveRecord
  has_many :expenses, dependent: :destroy

  validates :email,           presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :screen_name,     presence:      true,
                              uniqueness:    true,
                              format: { with: /\A[a-z0-9_]+\z/i, message: "は半角英数'_'を使用してください。"},
                              length: { in: 3..20 }

  auth_key 'screen_name'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  helper_method :current_user

  unless Rails.env.development?
    rescue_from ActiveRecord::RecordNotFound, :with => :access_denied
  end

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue
      sign_out
    end
  end

  def authenticate
    unless current_user
      redirect_to signin_path
    end
  end

  private

  def access_denied
    redirect_to '/404.html'
  end

  def sign_out
    @current_user = nil
    session[:user_id] = nil
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { @expenses = current_user.expenses.order(id: :asc) }
    end
  end

  def show
  end

  def create
    @expense = current_user.expenses.build(expense_params)

    if @expense.save
      redirect_to @expense
    else
      render json: { errors: @expense.errors.full_messages }
    end
  end

  def update
    if @expense.update(expense_params)
      redirect_to @expense
    else
      render json: { errors: @expense.errors.full_messages }
    end
  end

  def destroy
    @expense.destroy
    head :no_content
  end

  private

  def set_expense
    @expense = current_user.expenses.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:amount, :accrued_on)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate

  def new
    redirect_to root_url if current_user
  end

  def create
    user = User.find(env["omniauth.auth"]["uid"])
    session[:user_id] = user.id
    redirect_to expenses_url, notice: "Signed in!"
  end

  def destroy
    sign_out
    redirect_to signin_url, notice: "Signed out!"
  end

  def failure
    redirect_to signin_url, alert: "Authentication failed, please try again."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: %i(new create)

  before_action :set_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to signin_url, notice: "You've Successfully Signed up."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_url, notice: "Your profile has been successfully updated."
    else
      render action: 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:screen_name, :email, :password ,:password_confirmation)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/index.html.slim
.page-header
  h1 Listing expenses

script#expense-template type='text/x-template'
  .col-xs-6 v-class='editing: isAmountEditing'
    label.amount v-on='click: editAmount'
      | &yen;
      | {{amount}}
    input.edit.form-control v-model='editingValue' v-on='blur: update, keyup: update | key enter' v-if='isAmountEditing'
  .col-xs-4 v-class='editing: isAccruedOnEditing'
    label.accrued_on v-on='click: editAccruedOn'
      | {{accrued_on}}
    input.edit.form-control v-model='editingValue' v-on='blur: update, keyup: update | key enter' v-if='isAccruedOnEditing'
  .col-xs-2
    span.destroy-expense v-on='click: destroyExpense(this)'
      = fa_icon "trash-o"

#vue-expenses expensesUrl=expenses_url
  #new-expense.row
    .field
      .col-xs-8
        input.new-expense-field.form-control autofocus=true autocomplete='off' v-model='newExpense' v-on='keyup: createExpense | key enter'
      = fa_icon 'pencil'

  .expense.row v-component='expense' v-repeat="expenses | orderBy 'id' -1"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Zubora
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{ role: 'navigation' }
      .container-fluid
        .navbar-header
          = link_to 'Zubora', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          - if current_user
            %ul.nav.navbar-nav.navbar-right
              %li= link_to 'Sign out', signout_path, method: :delete
    .masthead
      = render partial: 'shared/flash'
    .container
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1'

    title Zubora
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    nav.navbar.navbar-default.navbar-static-top role='navigation'
      .container-fluid
        .navbar-header
          = link_to 'Zubora', root_path, class: 'navbar-brand'
          button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='.navbar-collapse'
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
        .collapse.navbar-collapse
          - if current_user
            ul.nav.navbar-nav.navbar-right
              li= link_to "@#{current_user.screen_name}", profile_path
              li= link_to 'Sign out', signout_path, method: :delete

    .container
      .masthead
        = render partial: 'shared/flash'

      = yield

app/views/shared/_flash.html.slim
- flash.each do |name, msg|
  - alert_class_name = case name
  - when 'notice'; 'alert alert-success'
  - when 'alert';  'alert alert-danger'
  - when 'info';   'alert alert-info'

  - if alert_class_name.present?
    div class=alert_class_name
      button.close data-dismiss='alert' type='button'
        = fa_icon('times-circle-o')
      = simple_format(msg)

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation.alert.alert-danger
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :screen_name
    = f.text_field :screen_name, class:'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class:'form-control'
  .form-group
    = f.label :password
    = f.password_field :password, class:'form-control'
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class:'form-control'
  .actions
    = f.submit class: "btn btn-large btn-primary pull-right btn-lg"

app/views/users/_form.html.slim
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation.alert.alert-danger
      h2
        = pluralize(@user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |message|
          li= message
  .form-group
    = f.label :screen_name
    = f.text_field :screen_name, class:'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class:'form-control'
  .form-group
    = f.label :password
    = f.password_field :password, class:'form-control'
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class:'form-control'
  .actions
    = f.submit class: "btn btn-large btn-primary pull-right btn-lg"

app/views/users/edit.html.slim
.page-header
  h1 Edit Profile

= render 'form'

app/views/users/new.html.haml
.page-header
  %h1 New user

= render 'form'

app/views/users/new.html.slim
.page-header
  h1 New user

= render 'form'